import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { BiBook } from "react-icons/bi";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = 0;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex w-full items-center justify-between  bg-slate-50  px-14 py-2 sm:col-span-2">
          <Link
            href="/"
            className="flex flex-col items-center font-mono text-xl font-semibold capitalize text-yellow-700 transition-colors  hover:text-yellow-950"
          >
            <span>next</span> bookStore
          </Link>

          <nav className="flex items-center gap-6  font-mono text-yellow-600">
            <Link
              href="/my-books"
              className="flex items-center gap-1 transition-colors delay-[21ms] hover:text-yellow-700 "
            >
              <BiBook /> MyBooks
            </Link>

            {!userId && (
              <>
                <Link
                  href="/sign-in"
                  className="transition-colors delay-[21ms] hover:text-yellow-700"
                >
                  Sign In
                </Link>
                <Link
                  href="/sign-up"
                  className="transition-colors delay-[21ms] hover:text-yellow-700"
                >
                  Sign Up
                </Link>
              </>
            )}

            {/* <UserButton after /> */}
          </nav>
        </header>

        <main>{children}</main>

        <footer className="h-24 bg-yellow-950 text-center text-yellow-500">
          @yonas github
        </footer>
      </body>
    </html>
  );
}
