import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="grid h-screen  sm:grid-rows-[auto_1fr] sm:grid-cols-[auto_1fr]  ">
          <header className="sm:col-span-2 bg-yellow-400">user search</header>

          <aside className="bg-rose-400 px-3">home myBooks logo footer</aside>
          <section className="px-3 overflow-y-scroll">{children}</section>
        </main>
      </body>
    </html>
  );
}
